### ISSUE TITLE
Request: Preserve Shulker Orientation

### ISSUE THREAD

**Issue by Thiana** [kgriff0n/dyeable-shulkers#1]
If it's possible, could the shulker's original orientation be restored when dying it? At the moment it sets the orientation of the new colored shulker to vertical.  This breaks storage in many of my farms since there isn't space for them to open vertically (the dyed shulker) compared to the original horizontal (the original shulker). 

Thanks.

**Comment by kgriff0n** [comment]
It's fixed, you can download it [here](https://modrinth.com/mod/dyeable-shulkers/version/1.0.1+1.20)

Thanks for your report !
